
-- Create languages table
CREATE TABLE public.languages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  native_name text NOT NULL,
  flag text NOT NULL DEFAULT '',
  is_active boolean NOT NULL DEFAULT false,
  translation_completeness integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.languages ENABLE ROW LEVEL SECURITY;

-- Anyone can view languages
CREATE POLICY "Anyone can view languages" ON public.languages FOR SELECT USING (true);

-- Admins can manage languages
CREATE POLICY "Admins can manage languages" ON public.languages FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

-- Seed 90+ world languages
INSERT INTO public.languages (code, name, native_name, flag, is_active, translation_completeness) VALUES
('en', 'English', 'English', '🇺🇸', true, 100),
('es', 'Spanish', 'Español', '🇪🇸', false, 85),
('fr', 'French', 'Français', '🇫🇷', false, 85),
('de', 'German', 'Deutsch', '🇩🇪', false, 85),
('pt', 'Portuguese', 'Português', '🇵🇹', false, 85),
('it', 'Italian', 'Italiano', '🇮🇹', false, 85),
('nl', 'Dutch', 'Nederlands', '🇳🇱', false, 85),
('ar', 'Arabic', 'العربية', '🇸🇦', false, 5),
('zh', 'Chinese', '中文', '🇨🇳', false, 5),
('ja', 'Japanese', '日本語', '🇯🇵', false, 5),
('ko', 'Korean', '한국어', '🇰🇷', false, 5),
('ru', 'Russian', 'Русский', '🇷🇺', false, 5),
('tr', 'Turkish', 'Türkçe', '🇹🇷', false, 5),
('pl', 'Polish', 'Polski', '🇵🇱', false, 5),
('sv', 'Swedish', 'Svenska', '🇸🇪', false, 5),
('hi', 'Hindi', 'हिन्दी', '🇮🇳', false, 5),
('th', 'Thai', 'ไทย', '🇹🇭', false, 5),
('af', 'Afrikaans', 'Afrikaans', '🇿🇦', false, 0),
('am', 'Amharic', 'አማርኛ', '🇪🇹', false, 0),
('az', 'Azerbaijani', 'Azərbaycan', '🇦🇿', false, 0),
('be', 'Belarusian', 'Беларуская', '🇧🇾', false, 0),
('bg', 'Bulgarian', 'Български', '🇧🇬', false, 0),
('bn', 'Bengali', 'বাংলা', '🇧🇩', false, 0),
('bs', 'Bosnian', 'Bosanski', '🇧🇦', false, 0),
('ca', 'Catalan', 'Català', '🇪🇸', false, 0),
('cs', 'Czech', 'Čeština', '🇨🇿', false, 0),
('cy', 'Welsh', 'Cymraeg', '🏴󠁧󠁢󠁷󠁬󠁳󠁿', false, 0),
('da', 'Danish', 'Dansk', '🇩🇰', false, 0),
('el', 'Greek', 'Ελληνικά', '🇬🇷', false, 0),
('et', 'Estonian', 'Eesti', '🇪🇪', false, 0),
('eu', 'Basque', 'Euskara', '🇪🇸', false, 0),
('fa', 'Persian', 'فارسی', '🇮🇷', false, 0),
('fi', 'Finnish', 'Suomi', '🇫🇮', false, 0),
('fil', 'Filipino', 'Filipino', '🇵🇭', false, 0),
('ga', 'Irish', 'Gaeilge', '🇮🇪', false, 0),
('gl', 'Galician', 'Galego', '🇪🇸', false, 0),
('gu', 'Gujarati', 'ગુજરાતી', '🇮🇳', false, 0),
('ha', 'Hausa', 'Hausa', '🇳🇬', false, 0),
('he', 'Hebrew', 'עברית', '🇮🇱', false, 0),
('hr', 'Croatian', 'Hrvatski', '🇭🇷', false, 0),
('hu', 'Hungarian', 'Magyar', '🇭🇺', false, 0),
('hy', 'Armenian', 'Հայերեն', '🇦🇲', false, 0),
('id', 'Indonesian', 'Bahasa Indonesia', '🇮🇩', false, 0),
('ig', 'Igbo', 'Igbo', '🇳🇬', false, 0),
('is', 'Icelandic', 'Íslenska', '🇮🇸', false, 0),
('ka', 'Georgian', 'ქართული', '🇬🇪', false, 0),
('kk', 'Kazakh', 'Қазақ', '🇰🇿', false, 0),
('km', 'Khmer', 'ភាសាខ្មែរ', '🇰🇭', false, 0),
('kn', 'Kannada', 'ಕನ್ನಡ', '🇮🇳', false, 0),
('ku', 'Kurdish', 'Kurdî', '🇮🇶', false, 0),
('ky', 'Kyrgyz', 'Кыргызча', '🇰🇬', false, 0),
('lo', 'Lao', 'ລາວ', '🇱🇦', false, 0),
('lt', 'Lithuanian', 'Lietuvių', '🇱🇹', false, 0),
('lv', 'Latvian', 'Latviešu', '🇱🇻', false, 0),
('mg', 'Malagasy', 'Malagasy', '🇲🇬', false, 0),
('mk', 'Macedonian', 'Македонски', '🇲🇰', false, 0),
('ml', 'Malayalam', 'മലയാളം', '🇮🇳', false, 0),
('mn', 'Mongolian', 'Монгол', '🇲🇳', false, 0),
('mr', 'Marathi', 'मराठी', '🇮🇳', false, 0),
('ms', 'Malay', 'Bahasa Melayu', '🇲🇾', false, 0),
('mt', 'Maltese', 'Malti', '🇲🇹', false, 0),
('my', 'Burmese', 'မြန်မာ', '🇲🇲', false, 0),
('ne', 'Nepali', 'नेपाली', '🇳🇵', false, 0),
('no', 'Norwegian', 'Norsk', '🇳🇴', false, 0),
('ny', 'Chichewa', 'Chichewa', '🇲🇼', false, 0),
('pa', 'Punjabi', 'ਪੰਜਾਬੀ', '🇮🇳', false, 0),
('ps', 'Pashto', 'پښتو', '🇦🇫', false, 0),
('ro', 'Romanian', 'Română', '🇷🇴', false, 0),
('rw', 'Kinyarwanda', 'Kinyarwanda', '🇷🇼', false, 0),
('si', 'Sinhala', 'සිංහල', '🇱🇰', false, 0),
('sk', 'Slovak', 'Slovenčina', '🇸🇰', false, 0),
('sl', 'Slovenian', 'Slovenščina', '🇸🇮', false, 0),
('so', 'Somali', 'Soomaali', '🇸🇴', false, 0),
('sq', 'Albanian', 'Shqip', '🇦🇱', false, 0),
('sr', 'Serbian', 'Српски', '🇷🇸', false, 0),
('su', 'Sundanese', 'Basa Sunda', '🇮🇩', false, 0),
('sw', 'Swahili', 'Kiswahili', '🇰🇪', false, 0),
('ta', 'Tamil', 'தமிழ்', '🇮🇳', false, 0),
('te', 'Telugu', 'తెలుగు', '🇮🇳', false, 0),
('tg', 'Tajik', 'Тоҷикӣ', '🇹🇯', false, 0),
('tk', 'Turkmen', 'Türkmen', '🇹🇲', false, 0),
('uk', 'Ukrainian', 'Українська', '🇺🇦', false, 0),
('ur', 'Urdu', 'اردو', '🇵🇰', false, 0),
('uz', 'Uzbek', 'Oʻzbek', '🇺🇿', false, 0),
('vi', 'Vietnamese', 'Tiếng Việt', '🇻🇳', false, 0),
('xh', 'Xhosa', 'isiXhosa', '🇿🇦', false, 0),
('yo', 'Yoruba', 'Yorùbá', '🇳🇬', false, 0),
('zu', 'Zulu', 'isiZulu', '🇿🇦', false, 0),
('ceb', 'Cebuano', 'Cebuano', '🇵🇭', false, 0),
('co', 'Corsican', 'Corsu', '🇫🇷', false, 0),
('eo', 'Esperanto', 'Esperanto', '🌍', false, 0),
('fy', 'Frisian', 'Frysk', '🇳🇱', false, 0),
('gd', 'Scottish Gaelic', 'Gàidhlig', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', false, 0),
('haw', 'Hawaiian', 'ʻŌlelo Hawaiʻi', '🇺🇸', false, 0),
('hmn', 'Hmong', 'Hmong', '🇱🇦', false, 0),
('ht', 'Haitian Creole', 'Kreyòl Ayisyen', '🇭🇹', false, 0),
('jw', 'Javanese', 'Basa Jawa', '🇮🇩', false, 0),
('la', 'Latin', 'Latina', '🇻🇦', false, 0),
('lb', 'Luxembourgish', 'Lëtzebuergesch', '🇱🇺', false, 0),
('mi', 'Maori', 'Te Reo Māori', '🇳🇿', false, 0),
('sm', 'Samoan', 'Gagana Samoa', '🇼🇸', false, 0),
('sn', 'Shona', 'chiShona', '🇿🇼', false, 0),
('sd', 'Sindhi', 'سنڌي', '🇵🇰', false, 0),
('st', 'Sesotho', 'Sesotho', '🇱🇸', false, 0),
('tl', 'Tagalog', 'Tagalog', '🇵🇭', false, 0),
('tt', 'Tatar', 'Татар', '🇷🇺', false, 0),
('ug', 'Uyghur', 'ئۇيغۇرچە', '🇨🇳', false, 0),
('yi', 'Yiddish', 'ייִדיש', '🇮🇱', false, 0);
